export { default as Dashboard } from './Dashboard/dashboard'
export { default as Login } from './Login/login'
export { default as TaskListing } from './TaskListing/task-listing'
export { default as TaskRegistration } from './TaskRegistration/task-registration'
export { default as UserRegistration } from './UserRegistration/user-registration'
